// <auto-generated />
namespace CreditInfoAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addContractData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addContractData));
        
        string IMigrationMetadata.Id
        {
            get { return "202001031442139_addContractData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
